on:
  workflow_dispatch:

jobs:
  setup_prod:
    environment: prd
    name: 'Terraform Prod'
    runs-on: ubuntu-latest

    # using bash and the iac folder by default
    defaults:
      run:
        shell: bash
        working-directory: ./iac

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize the prod backend
    - name: Terraform Init
      run: terraform init -backend-config=prd.backend.hcl
    
    
    # Initialize the prod backend
    - name: Terraform Init
      run: terraform init -backend-config=prd.backend.hcl
    
    
